kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-efs
provisioner: ts-eks/aws-efs
reclaimPolicy: Retain
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: efs-mlflow
#   annotations:
#     volume.beta.kubernetes.io/storage-class: "aws-efs"
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 20Gi
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: efs-airflow
#   annotations:
#     volume.beta.kubernetes.io/storage-class: "aws-efs"
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 20Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-airflow-dags
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-airflow-logs
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
---