apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ts-ingress-evalm-dashboard-https
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "600"
    #cert-manager.io/cluster-issuer: "letsencrypt-prod"
    #nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
#   tls:
#     - hosts:
#         - ad6a50d1faa5811ea8e6e0a95ea484b3-d431ef5d286dfe22.elb.us-east-1.amazonaws.com
#       secretName: ts-eks-nlb
  rules:
    - host: {{alb_endpoint}}
      http:
        paths:
          - path: /ts/eval/?(.*)
            backend:
              serviceName: evalm-dashboard
              servicePort: 8080
