channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip=18.1
    - more-itertools=8.4.0
    - setuptools_scm=3.4.*
    - numpy=1.19.1
    - pandas=1.0.5
    - s3fs=0.5.0
    - pyyaml=5.3.1
    - pip:
        - metaflow==2.2.2
