repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.1
    hooks:
    -   id: seed-isort-config

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
    -   id: isort

-   repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
        - id: autoflake
          args: ['--in-place', '--remove-unused-variable']

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
        - id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      args: ['--max-line-length=88', '--ignore=E203,W503',  '--exclude=ts_forecast/core/model/__init__.py,deploy/airflow/dags_template/airflow_template.py']
